apiVersion: apps/v1
kind: Deployment
metadata: 
  name: my-app-depl
spec:
  selector:
    matchLables:
      app: react-app
  replicas: 1
  templates:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: princedeka/cryptoimg:v1
---
apiVersion: v1
kind: Service
metadata: 
  name: my-react-app-srv
spec:
  type: NodePort
  selector:
    app: react-app
  ports: 
    - name: my-app
      port: 3000
      targetPort: 3000